<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wqq" ignored="0" name="t2" tests="5" failures="3" timestamp="2020-12-07T10:28:33 CST" time="0.037" errors="0">
  <testcase name="test1" time="0.006" classname="com.webtest.demo.Testng_xslt"/>
  <testcase name="test2" time="0.001" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.Testng_xslt.test2(Testng_xslt.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.demo.Testng_xslt"/>
  <testcase name="test4" time="0.001" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.webtest.demo.Testng_xslt.test4(Testng_xslt.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.001" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
at com.webtest.demo.Testng_xslt.test5(Testng_xslt.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- t2 -->
