<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-97AVU8KE" ignored="0" name="test1" tests="5" failures="3" timestamp="2020-12-07T10:42:35 CST" time="0.046" errors="0">
  <testcase name="test1" time="0.006" classname="com.webtest.demo.demo"/>
  <testcase name="test2" time="0.001" classname="com.webtest.demo.demo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.demo.test2(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.demo.demo"/>
  <testcase name="test4" time="0.001" classname="com.webtest.demo.demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.webtest.demo.demo.test4(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="com.webtest.demo.demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
at com.webtest.demo.demo.test5(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- test1 -->
