<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wqq" ignored="0" name="t2" tests="5" failures="3" timestamp="2020-12-10T21:13:46 CST" time="0.023" errors="0">
  <testcase name="test1" time="0.003" classname="com.webtest.demo.Testng_xslt"/>
  <testcase name="test2" time="0.0" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.Testng_xslt.test2(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.demo.Testng_xslt"/>
  <testcase name="test4" time="0.0" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.webtest.demo.Testng_xslt.test4(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="com.webtest.demo.Testng_xslt">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
at com.webtest.demo.Testng_xslt.test5(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- t2 -->
